"""part2_catalog_search_cart_wishlist_completion

Revision ID: e6118c11ebbc
Revises: 3b81ac6fe22a
Create Date: 2026-10-07 22:21:06.770514

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6118c11ebbc'
down_revision: Union[str, None] = '3b81ac6fe22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Product specification details (JSON string in a text column).
    op.add_column('products', sa.Column('specifications', sa.Text(), nullable=True))

    # Cart coupon support.
    op.add_column('carts', sa.Column('coupon_id', sa.String(), nullable=True))
    op.add_column(
        'carts',
        sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'),
    )
    op.create_index(op.f('ix_carts_coupon_id'), 'carts', ['coupon_id'], unique=False)
    op.create_foreign_key('carts_coupon_id_fkey', 'carts', 'coupons', ['coupon_id'], ['id'])
    op.create_check_constraint(
        'ck_cart_discount_nonneg', 'carts', 'discount_amount >= 0'
    )

    # Order coupon support (discount applied at checkout).
    op.add_column('orders', sa.Column('coupon_id', sa.String(), nullable=True))
    op.add_column(
        'orders',
        sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'),
    )
    op.create_index(op.f('ix_orders_coupon_id'), 'orders', ['coupon_id'], unique=False)
    op.create_foreign_key('orders_coupon_id_fkey', 'orders', 'coupons', ['coupon_id'], ['id'])
    # ### end Alembic commands ###

    # PostgreSQL search indexes for catalog ILIKE search. The extension is
    # created if missing; GIN trigram indexes make '%term%' searches fast.
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_products_name_trgm "
        "ON products USING gin (name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_products_description_trgm "
        "ON products USING gin (description gin_trgm_ops)"
    )

    # Filter/sort support (model declares these too).
    op.create_index(op.f('ix_products_rating'), 'products', ['rating'], unique=False)
    op.create_index(op.f('ix_products_discount_price'), 'products', ['discount_price'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'specifications')
    op.drop_constraint('orders_coupon_id_fkey', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_coupon_id'), table_name='orders')
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'coupon_id')
    op.drop_constraint('carts_coupon_id_fkey', 'carts', type_='foreignkey')
    op.drop_index(op.f('ix_carts_coupon_id'), table_name='carts')
    op.drop_column('carts', 'discount_amount')
    op.drop_column('carts', 'coupon_id')
    # ### end Alembic commands ###
    op.drop_index(op.f('ix_products_discount_price'), table_name='products')
    op.drop_index(op.f('ix_products_rating'), table_name='products')
    op.execute('DROP INDEX IF EXISTS ix_products_description_trgm')
    op.execute('DROP INDEX IF EXISTS ix_products_name_trgm')
    op.drop_constraint('ck_cart_discount_nonneg', 'carts', type_='check')
